### ISSUE TITLE
Wrong parser API usage for mqtt and amqp

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#13]
#### Describe the bug
Due to following errors in API usage generation falls down:
`.bindings('amqp')` instead of `.binding('amqp')`
`.bindings('mqtt')` instead of `.binding('mqtt')`
`variables(port)` instead of `variable('port')`

#### How to Reproduce
Run with 
```
servers:
  production:
    url: api.streetlights.smartylighting.com:{port}
    protocol: mqtt
    description: Test broker
    variables:
      port:
        description: Secure connection (TLS) is available through port 8883.
        default: '1883'
        enum:
          - '1883'
          - '8883'
```

#### Expected behavior
Template generates without errors
