### ISSUE TITLE
$ref field is not processed and AnonymousSchema is generated

### ISSUE THREAD

**Issue by leodennis** [asyncapi/java-spring-template#264]
#### Describe the bug

When generating code an AnonymousSchema is created even though classes are referenced using `$ref`. 

I did already create an issue at the springwolf project [(issue-link)](https://github.com/springwolf/springwolf-core/issues/119) but it seems the problem is not the generated AsyncAPI specification but rather that the `$ref` field is not processed or not processecd correctly.

#### How to replicate the bug

I use springwolf to create a AsyncAPI specification out of Kafka listners (in java spring). I created some simple test classes:
```
@Component
public class KafkaFirebaseConsumer {
    @KafkaListener(topics = "Test", groupId = "test-group")
    public void listenTopicFirebase(TestDto payload) {
        // nothing to do
    }
}
```
```
public class TestDto {
    private String name;
    private List<ListObject> myList;
    // constructor, getters and setters
}
```
```
public class ListObject {
    private String stringField;
    private int numberField;
    // constructor, getters and setters
}
```

Springwolf now generates the following valid AsyncAPI specification json:
```
{
  "asyncapi": "2.0.0",
  "info": {
    "title": "Test",
    "version": "1.0.0"
  },
  "servers": {
    "kafka": {
      "url": "127.0.0.1:28015",
      "protocol": "kafka"
    }
  },
  "channels": {
    "test": {
      "publish": {
        "operationId": "test_publish_listenTopicTest",
        "description": "Auto-generated description",
        "bindings": {
          "kafka": {
            "groupId": {
              "type": "string",
              "enum": [
                "test-group"
              ]
            }
          }
        },
        "message": {
          "name": "com.test.model.dto.TestDto",
          "title": "TestDto",
          "payload": {
            "$ref": "#/components/schemas/TestDto"
          },
          "headers": {
            "$ref": "#/components/schemas/HeadersNotDocumented"
          }
        }
      },
      "bindings": {
        "kafka": {}
      }
    }
  },
  "components": {
    "schemas": {
      "HeadersNotDocumented": {
        "type": "object",
        "properties": {},
        "example": {},
        "exampleSetFlag": true,
        "types": [
          "object"
        ]
      },
      "ListObject": {
        "type": "object",
        "properties": {
          "stringField": {
            "type": "string",
            "exampleSetFlag": false,
            "types": [
              "string"
            ]
          },
          "numberField": {
            "type": "integer",
            "format": "int32",
            "exampleSetFlag": false,
            "types": [
              "integer"
            ]
          }
        },
        "example": {
          "stringField": "string",
          "numberField": 0
        },
        "exampleSetFlag": true
      },
      "TestDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "exampleSetFlag": false,
            "types": [
              "string"
            ]
          },
          "myList": {
            "type": "array",
            "exampleSetFlag": false,
            "items": {
              "$ref": "#/components/schemas/ListObject",
              "exampleSetFlag": false
            },
            "types": [
              "array"
            ]
          }
        },
        "example": {
          "name": "string",
          "myList": [
            {
              "stringField": "string",
              "numberField": 0
            }
          ]
        },
        "exampleSetFlag": true
      }
    }
  },
  "tags": []
}
```
Now when I generate code with `ag test.json @asyncapi/java-spring-template -o Output` 
I get the following message:
```
com/asyncapi/model/AnonymousSchema3.java

This may be a result of explicit (composition, inheritance, array items) Schema Object definition e.g.

    schemas:
      NamedObject:
      type: object
        properties:
          field:
            type: array
            items:
              type: object #Anonymous object
              properties:
                field:
                  type: string

OR

    messages:
      Message:
        payload:
          type: object #Anonymous object
          properties:

Please move such elements to child of "schemas:" to define proper names.
If changing of data model is not possible, you may use "$id" to set name e.g.

    properties:
      field:
        type: array
        items:
          $id: ArrayElement #Name of object
          type: object
          properties:
            field:
              type: string

```

And you can see AnonymousSchema3 instead of  ListObject  in the class:
```
public class TestDto {   
    private @Valid String name;   
    private @Valid List<AnonymousSchema3> myListList;
    // other methods
}
```

#### Expected behavior
Code generation succeeds and no AnonymousSchema is created.

**Edit**: The problem also exists without array but also using `$ref` like
```
"data": {
    "$ref": "#/components/schemas/DataClass",
    "exampleSetFlag": false
 }
```
