### ISSUE TITLE
Support for Pulsar

### ISSUE THREAD

**Issue by bob-sheknowdas** [asyncapi/java-spring-template#56]
#### Reason/Context
It would be nice to have support for [Apache Pulsar](https://pulsar.apache.org/) (Kafka successor).

#### Description
One could build uppon [pulsar-java-spring-boot-starter](https://github.com/majusko/pulsar-java-spring-boot-starter) for the templates.
I don't know your policies on external libraries, though...

api.yml would probably look like this:
```
servers:
  my-pulsar:
    url: {protocol}://my.pulsar.domain:{port}
    protocol: {protocol}
    description: my pulsar broker
    variables:
      port:
        default: '6650'
      protocol:
        default: 'pulsar'
```
